from datetime import datetime

from langchain_groq import ChatGroq
from langchain.messages import HumanMessage, SystemMessage

from config import POWERFUL_MODEL
from state import AgentState

_llm = ChatGroq(model=POWERFUL_MODEL, temperature=0.4)

_SYSTEM = """
You are a Goldman Sachs equity research analyst producing an institutional
research note for professional investors.

Strict rules:
- Use ONLY the data provided in the prompt — no invented facts
- Every statistic must come from the source data
- Use [Source: Yahoo Finance] [Source: SEC 10-K] [Source: News] inline citations
- Professional but readable prose — avoid jargon for its own sake
- Total word count: 450-520 words in the body sections
- End with a single bold verdict line
"""


def writer_node(state: AgentState) -> dict:

    ticker       = state["ticker"]
    company_name = state.get("company_name", ticker)
    sector       = state.get("sector", "Unknown")
    today        = datetime.now().strftime("%B %d, %Y")

    print(f"\n[Writer] Composing research note for {company_name}...")

    headlines_text = "\n".join(state.get("news_headlines", [])[:5])

    user = f"""
Write a professional equity research note using ONLY the verified data below.

SOURCE DATA:

--- Yahoo Finance Metrics ---
{state.get("financial_data", "Not available")}

--- Recent News Headlines ---
{headlines_text if headlines_text else "No news available"}

--- Bull Thesis (Internal Analysis) ---
{state.get("bull_thesis", "Not available")}

--- Bear Thesis (Internal Analysis) ---
{state.get("bear_thesis", "Not available")}

--- Risk Factors (SEC 10-K Filing) ---
{state.get("risk_factors", "Not available")}

--- Management Guidance (SEC Filing) ---
{state.get("management_guidance", "Not available")}

---
FORMAT YOUR RESPONSE EXACTLY AS FOLLOWS:

# {company_name} ({ticker}) | Equity Research Note
**Sector:** {sector} | **Date:** {today} | **Prepared by:** FinSight AI

---

## Recommendation
[BUY / HOLD / SELL — one sentence rationale]

---

## Key Statistics
[List 4-5 of the most important metrics from the Yahoo Finance data in a clean format]

---

## Bull Case
[150-180 words. Use specific numbers and cite [Source: Yahoo Finance] or [Source: SEC 10-K] inline]

---

## Bear Case
[150-180 words. Use specific risks with citations]

---

## Key Risks
[Bullet list of exactly 3 risks from the SEC filing with one sentence each]

---

## Analyst Verdict
**[One bold sentence with rating and price target direction. Example: HOLD — Risk/reward balanced at current valuation; await clearer margin trajectory before adding exposure.]**

---
*Disclaimer: This note is generated by FinSight AI for educational purposes only.
It does not constitute investment advice. Sources: Yahoo Finance, Tavily Web Search,
SEC EDGAR. Data as of {today}.*
"""

    messages = [
        SystemMessage(content=_SYSTEM),
        HumanMessage(content=user),
    ]

    response      = _llm.invoke(messages)
    final_report  = response.content.strip()

    print(f"[Writer] Report generated — {len(final_report)} characters")

    return {
        "final_report": final_report,
    }